# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-04-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title_prefix", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=200)),
                ("long_description", models.TextField(blank=True)),
                ("update_frequency", models.CharField(max_length=100)),
                ("temporal_coverage", models.CharField(max_length=100)),
                ("data_owner", models.CharField(max_length=100)),
                ("publisher_name", models.CharField(max_length=100)),
                ("publisher_email", models.EmailField(blank=True, max_length=254)),
                ("source_database", models.CharField(max_length=100)),
                ("source_table", models.CharField(max_length=100)),
                ("source_query", models.TextField(blank=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="meta_forms.dataset",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="tables", to="meta_forms.tag"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataset",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="meta_forms.project",
            ),
        ),
    ]
