# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-04-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meta_forms", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="long_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="table",
            name="publisher_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="table",
            name="source_query",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="meta_forms.table",
                    ),
                ),
            ],
        ),
    ]
