# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-04-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_forms", "0004_alter_table_long_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="contains_dict",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="is_sensitive",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="column",
            name="measurement_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="original_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="column",
            name="temporal_coverage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="type",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
