# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-04-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_forms", "0005_column_comments_column_contains_dict_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
