# -*- coding: utf-8 -*-
# Generated by Django 4.0.4 on 2022-05-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_forms", "0006_alter_column_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("path", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="column",
            name="is_sensitive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="table",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories", to="meta_forms.category"
            ),
        ),
    ]
